---
title: "map"
author: "Jonathan Glass"
date: "12/9/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```




```{r}
## Import data: Source from Johns Hopkins Github data
confirmed_data <- read.csv("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv")
deaths_data <- read.csv("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv")
recovered_data <- read.csv("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_recovered_global.csv")


# Data cleaning: To create country level and global level data
library(tidyr)
library(dplyr)
## Country level
confirmed <- confirmed_data %>% gather(key="date", value="confirmed", -c(Country.Region, Province.State, Lat, Long)) %>% group_by(Country.Region, date) %>% summarize(confirmed=sum(confirmed))

deaths <- deaths_data %>% gather(key="date", value="deaths", -c(Country.Region, Province.State, Lat, Long)) %>% group_by(Country.Region, date) %>% summarize(deaths=sum(deaths))

recovered <- recovered_data %>% gather(key="date", value="recovered", -c(Country.Region, Province.State, Lat, Long)) %>% group_by(Country.Region, date) %>% summarize(recovered=sum(recovered))


# Create final country level dataset: combine all three variables
country_data <- full_join(confirmed, deaths) %>% full_join(recovered)
country_data$date <- country_data$date %>% sub("X", "", .) %>% as.Date("%m.%d.%y")

# Create new variable: number of days
country_data <- country_data %>% group_by(Country.Region) %>% mutate(cumconfirmed=cumsum(confirmed), days = date - first(date) + 1)

## World level
world_data <- country_data %>% group_by(date) %>% summarize(confirmed=sum(confirmed), cumconfirmed=sum(cumconfirmed), deaths=sum(deaths), recovered=sum(recovered)) %>% mutate(days = date - first(date) + 1)

# Specific countries levels
Albania <- country_data %>% filter(Country.Region=="Albania")
Australia <- country_data %>% filter(Country.Region=="Australia")
Brazil <- country_data %>% filter(Country.Region=="Brazil")
China <- country_data %>% filter(Country.Region=="China")
Cuba <- country_data %>% filter(Country.Region=="Cuba")
Egypt <- country_data %>% filter(Country.Region=="Egypt")
France <- country_data %>% filter(Country.Region=="France")
Iceland <- country_data %>% filter(Country.Region=="Iceland")
Indonesia <- country_data %>% filter(Country.Region=="Indonesia")
Italy <- country_data %>% filter(Country.Region=="Italy")
Japan <- country_data %>% filter(Country.Region=="Japan")
US <- country_data %>% filter(Country.Region=="US")



```
```{r}
#data cordinates
latitude<-confirmed_data$Lat
longitude<-confirmed_data$Long


```




```{r, warning=FALSE}
#install.packages("rworldmap")
library(rworldmap)
library(ggplot2)
# get map
worldmap <- getMap(resolution = "coarse")
# plot world map
plot(worldmap, col = "lightgrey", 
     fill = T, border = "darkgray",
     xlim = c(-180, 180), ylim = c(-90, 90),
     bg = "aliceblue",
     asp = 1, wrap=c(-180,180))
lines(longitude,latitude,type = "p",col="red",pch=21, bg=24, cex=confirmed_data$X12.8.20/9990000, lwd=.4,)

#changing cex as a vector of 12/8s data divided by 9,990,000 (for scale)
#shows well in rmarkdown file but not as well in pdf

```